const datos = [
  {
    country: "Afghanistan",
    code: "AFG",
    year: 2000,
    wind: 0,
    hydro: 0.31,
    solar: 0,
    other: 0,
  },
  {
    country: "Afghanistan",
    code: "AFG",
    year: 2001,
    wind: 0,
    hydro: 0.5,
    solar: 0,
    other: 0,
  },
  {
    country: "Albania",
    code: "ALB",
    year: 1990,
    wind: 0,
    hydro: 2.85,
    solar: 0,
    other: 0,
  },
  {
    country: "Algeria",
    code: "DZA",
    year: 1965,
    wind: 0,
    hydro: 0.4,
    solar: 0,
    other: 0,
  },
  {
    country: "American Samoa",
    code: "ASM",
    year: 2000,
    wind: 0,
    hydro: 0,
    solar: 0,
    other: 0,
  },
  {
    country: "Angola",
    code: "AGO",
    year: 2000,
    wind: 0,
    hydro: 0.9,
    solar: 0,
    other: 0,
  },
  {
    country: "Antigua and Barbuda",
    code: "ATG",
    year: 2000,
    wind: 0,
    hydro: 0,
    solar: 0,
    other: 0,
  },
  {
    country: "Argentina",
    code: "ARG",
    year: 1965,
    wind: 0,
    hydro: 1.225,
    solar: 0,
    other: 0,
  },
  {
    country: "Armenia",
    code: "ARM",
    year: 2000,
    wind: 0,
    hydro: 1.25,
    solar: 0,
    other: 0,
  },
  {
    country: "Aruba",
    code: "ABW",
    year: 2000,
    wind: 0,
    hydro: 0,
    solar: 0,
    other: 0,
  },
];

let mediaElectricidadHydro =
  datos.map((d) => d.hydro).reduce((a, b) => a + b) / datos.length;

console.log(mediaElectricidadHydro);
